; PlatformIO Project Configuration File
[env:esp32-s3-lcd-3_16]
platform = espressif32
board = esp32-s3-devkitc-1
framework = espidf
monitor_speed = 115200

board_build.arduino.memory_type = qio_opi 
board_build.flash_mode = dio
board_upload.flash_size = 16MB

build_flags = 
    -D BOARD_HAS_PSRAM
    -D CORE_DEBUG_LEVEL=5
    -D CONFIG_I2C_SUPPRESS_DEPRECATE_WARN=1
    -D CONFIG_TINYUSB_ENABLED=1
    -D CONFIG_TINYUSB_MSC_ENABLED=1
    -D CONFIG_TINYUSB_MSC_BUFSIZE=512
